--authorization
CREATE TABLE IF NOT EXISTS "authorization"();
ALTER TABLE "authorization" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;

--ctrc
CREATE TABLE IF NOT EXISTS "ctrc"();
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "queueId" UUID;
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "serieNumeroCTRC" VARCHAR(30);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "serieCt" INTEGER;
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "numeroCt" BIGINT;
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "tipoDocumento" VARCHAR(25);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "pracaExpedidora" VARCHAR(4);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "unidadeEmissora" VARCHAR(3);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "dataEmissao" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "dataAutorizacao" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "login" VARCHAR(15);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "numeroControle" VARCHAR(15);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "placaColeta" VARCHAR(20);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "chaveCt" VARCHAR(44);

ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "cnpjRemetente" VARCHAR(14);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "nomeRemetente" VARCHAR(70);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "enderecoRemetente" VARCHAR(100);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "bairroRemetente" VARCHAR(50);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "setorColeta" VARCHAR(5);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "cidadeRemetente" VARCHAR(40);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "ufRemetente" VARCHAR(2);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "cepRemetente" VARCHAR(8);

ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "cnpjExpedidor" VARCHAR(14);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "nomeExpedidor" VARCHAR(70);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "cidadeExpedidor" VARCHAR(40);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "ufExpedidor" VARCHAR(2);

ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "cnpjPagador" VARCHAR(14);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "nomePagador" VARCHAR(70);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "enderecoPagador" VARCHAR(100);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "bairroPagador" VARCHAR(50);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "cidadePagador" VARCHAR(40);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "ufPagador" VARCHAR(2);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "fonePagador" VARCHAR(12);
ALTER TABLE "ctrc" ADD COLUMN IF NOT EXISTS "segmentoPagador" VARCHAR(30);

--queue
CREATE TABLE IF NOT EXISTS "queue"();
ALTER TABLE "queue" ADD COLUMN IF NOT EXISTS "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY;
ALTER TABLE "queue" ADD COLUMN IF NOT EXISTS "authorizationId" UUID;
ALTER TABLE "queue" ADD COLUMN IF NOT EXISTS "code" VARCHAR(10);
